name: Deploy to VPS

on:
  push:
    branches:
      - master  # Change this to your main brancht

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no deployer-landry@${{ secrets.VPS_HOST }} << 'EOF'
            # Navigate to your application directory
            cd /var/www/my-apps/parika-app-client

            # Mark the directory as safe
            git config --global --add safe.directory /var/www/my-apps/parika-app-client

            # Pull the latest code
            git pull origin master

            # Navigate to the directory where docker-compose.yml file is located
            cd /var/www/my-apps/

            # Rebuild and restart the Spring Boot container
            docker-compose up -d --build react-app
            
          EOF
